import type { Metadata } from "next";
import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "FULBO",
  description: "Generated by appncy",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="dark container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] bg-background px-4 font-sans antialiased">
        <header className="flex items-center justify-between">
          <Link className="text-xl font-bold leading-[4rem]" href="/">Fulbo--mdq</Link>
          <nav>
            <ul className="flex gap-4 opacity-70">
              <li>
                <Link href="/">PARTIDOS</Link>
              </li>
              <li>
                <Link href="/jugadores">JUGADORES</Link>
              </li>
              <li>
                <Link href="/armador">ARMADOR DE EQUIPOS</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} fulbo--mdq
        </footer>
      </body>
    </html>
  );
}
